### ISSUE TITLE
PyPI Package?

### ISSUE THREAD

**Issue by achen353** [speechio/chinese_text_normalization#10]
Hey, I really love your work here. It is super helpful for what I'm working on right now.

Are you guys planning to release a PyPI package of this in the near future?

**Comment by dophist** [comment]
There is no such plan in near future, the license is pretty flexible though, so anyone can wrap the code into a PyPI package of their own, I'm OK with that.

**Comment by achen353** [comment]
@dophist That's really kind of you! I'd love to help you wrap the code into a PyPI package when I get my tasks at hand done.
