### ISSUE TITLE
Can't process Chinese input like "万" or "点"

### ISSUE THREAD

**Issue by hs79hs** [speechio/chinese_text_normalization#7]
Hi, thanks for great work. But when I test `run_cn.sh`, seems it can't process "万" and "点", for example,
![image](https://user-images.githubusercontent.com/6645793/99603227-ff143300-2a56-11eb-9d24-768523e6d872.png)

**Comment by dophist** [comment]
Thanks for pointing out, unlike the TN part, current ITN grammars are preliminary, they need to be improved definitely.  Appreciated if you can make PR over this, happy to merge.

**Comment by xishaoheng** [comment]
Is therre c++ version?
